// HISTORY — исторические эпохи и страны (стиль «История»)
const HISTORY = [
  { id: 'ancient_egypt', name: '🏛️ Древний Египет', prompt: 'Ancient Egypt, pyramids and pharaohs, golden desert, hieroglyphics, dramatic epic cinematic movie shot' },
  { id: 'wild_west', name: '🤠 Дикий Запад', prompt: 'American Wild West, dusty saloon, cowboy hat and horse, tumbleweed, golden sunset, epic western cinematic shot' },
  { id: 'ancient_rome', name: '⚔️ Древний Рим', prompt: 'Ancient Rome, Colosseum and Roman soldiers in armor, marble columns, togas, epic historical cinematic shot' },
  { id: 'medieval_europe', name: '🏰 Средневековая Европа', prompt: 'Medieval Europe, knights in shining armor, castle siege, king and queen, epic historical cinematic shot' },
  { id: 'feudal_japan', name: '🗡️ Феодальная Япония', prompt: 'Feudal Japan, samurai warriors in armor, cherry blossoms, pagoda castle, epic Asian historical cinematic shot' },
  { id: 'soviet_ussr', name: '🔴 Советский Союз', prompt: 'Soviet USSR era, Red Square, communist propaganda posters, workers and soldiers, dramatic period cinematic shot' },
  { id: 'viking_age', name: '⛵ Эпоха викингов', prompt: 'Viking age, longships on fjords, horned helmets, Norse warriors, rugged Scandinavian landscape, epic cinematic shot' },
  { id: 'pirate_golden', name: '🏴‍☠️ Золотой век пиратов', prompt: 'Golden Age of Piracy, pirate ship on Caribbean sea, treasure map, skull flag, swashbuckling cinematic shot' },
  { id: 'roaring_20s', name: '🥂 США 1920-е', prompt: 'Roaring Twenties America, flapper dresses, speakeasy bar, jazz music, Gatsby style, vintage cinematic shot' },
  { id: 'ancient_greece', name: '🏛️ Древняя Греция', prompt: 'Ancient Greece, Parthenon, philosophers in white robes, Olympic games, Mediterranean blue, epic cinematic shot' },
  { id: 'silk_road', name: '🐫 Великий шёлковый путь', prompt: 'Silk Road trade route, caravans crossing Central Asian deserts, Samarkand markets, merchants and camels, epic cinematic shot' },
  { id: 'colonial_india', name: '🕌 Британская Индия', prompt: 'British colonial India, maharajas and British officers, Taj Mahal, tea plantations, period drama cinematic shot' },
  { id: 'maya_empire', name: '🗿 Империя Майя', prompt: 'Mayan civilization, step pyramids in jungle, calendar stone, colorful headdresses, epic historical cinematic shot' },
  { id: 'napoleonic_wars', name: '🎖️ Наполеоновские войны', prompt: 'Napoleonic Wars era, French and Russian armies, battlefield smoke, marching soldiers, epic war cinematic shot' },
  { id: 'ice_age', name: '❄️ Ледниковый период', prompt: 'Ice Age, mammoths in snow, cavemen in furs, frozen landscape, prehistoric survival, dramatic cinematic shot' },
  { id: 'gold_rush', name: '⛏️ Золотая лихорадка', prompt: 'California Gold Rush, prospectors with pans, mining camps, snowy Sierra Nevada, adventurous cinematic shot' },
  { id: 'byzantine', name: '🕌 Византийская империя', prompt: 'Byzantine Empire, Hagia Sophia, Greek fire, imperial mosaics, Constantinople, epic medieval cinematic shot' },
  { id: 'samurai_japan', name: '🗡️ Эпоха Сэнгоку', prompt: 'Sengoku period Japan, samurai clans at war, castle siege, katana duel, dramatic Japanese cinematic shot' },
  { id: 'industrial_revolution', name: '🏭 Промышленная революция', prompt: 'Industrial Revolution, steam engines and factories, Victorian London smog, workers and machines, cinematic shot' },
  { id: 'renaissance', name: '🎨 Эпоха Возрождения', prompt: 'Italian Renaissance, Florence cathedral, artists studios, Medici palace, humanism and art, dramatic cinematic shot' },
  { id: 'cold_war', name: '☢️ Холодная война', prompt: 'Cold War era, Berlin Wall, nuclear threat, spies and diplomacy, 1960s tension, dramatic thriller cinematic shot' },
  { id: 'kievan_rus', name: '⛪ Киевская Русь', prompt: 'Kievan Rus, ancient Slavic princes, golden domed cathedrals, boyars and druzhina warriors, historical cinematic shot' },
  { id: 'russian_empire_19th', name: '👑 Российская империя XIX век', prompt: 'Russian Empire 19th century, Winter Palace, tsar and nobility, sleigh in snowy St Petersburg, epic cinematic shot' },
  { id: 'wild_siberia', name: '🌲 Освоение Сибири', prompt: 'Russian exploration of Siberia, fur traders and Cossacks, taiga forest, frozen rivers, adventurous cinematic shot' },
  { id: 'ancient_china', name: '🏯 Древний Китай', prompt: 'Ancient Imperial China, Forbidden City, Terracotta Army, silk robes, misty mountains, epic historical cinematic shot' },
  { id: 'victorian_england', name: '🎩 Викторианская Англия', prompt: 'Victorian England, London fog, horse carriages, top hats and corsets, gas lamps, atmospheric period cinematic shot' },
  { id: 'spartans', name: '🛡️ Спарта', prompt: 'Ancient Sparta, hoplite warriors with shields and spears, Leonidas, Thermopylae pass, epic battle cinematic shot' },
  { id: 'mexican_revolution', name: '🌵 Мексиканская революция', prompt: 'Mexican Revolution, Pancho Villa and Zapata, sombreros and rifles, dusty towns, dramatic historical cinematic shot' },
  { id: 'egypt_1920s', name: '🕌 Египет 1920-х', prompt: '1920s Egypt, Cairo souks, discovery of Tutankhamun tomb, colonial explorers, golden age cinematic shot' },
  { id: 'stone_age', name: '🪨 Каменный век', prompt: 'Stone Age, prehistoric tribe, cave paintings, hunting mammoths, fire discovery, primal cinematic shot' },
  { id: 'mongol_empire', name: '🐎 Монгольская империя', prompt: 'Mongol Empire, Genghis Khan, yurts on steppe, horse archers, vast Asian plains, epic historical cinematic shot' },
  { id: 'french_revolution', name: '🇫🇷 Французская революция', prompt: 'French Revolution, storming the Bastille, guillotine, mobs in Paris streets, liberty equality fraternity, dramatic cinematic shot' },
  { id: 'prohibition_usa', name: '🍸 Сухой закон США', prompt: 'Prohibition era USA, gangsters with tommy guns, speakeasy bars, Al Capone, bootleg whiskey, crime cinematic shot' },
  { id: 'ottoman_empire', name: '🕌 Османская империя', prompt: 'Ottoman Empire, Topkapi Palace, sultan and harem, Janissaries, Istanbul skyline, epic historical cinematic shot' },
  { id: 'celtic_tribes', name: '☘️ Кельтские племена', prompt: 'Ancient Celtic tribes, druids in forest, stone circles, blue woad warriors, misty British isles, cinematic shot' },
  { id: 'cuban_revolution', name: '🇨🇺 Кубинская революция', prompt: 'Cuban Revolution, Fidel Castro and Che Guevara, vintage cars in Havana, cigar smoke, retro cinematic shot' },
  { id: 'ww1_trenches', name: '⚰️ Первая мировая', prompt: 'World War I trenches, muddy battlefield, soldiers in gas masks, poppy fields, poignant war cinematic shot' },
  { id: 'ww2_europe', name: '🎖️ Вторая мировая', prompt: 'World War II Europe, D-Day landings, soldiers in combat, destroyed cities, dramatic war cinematic shot' },
  { id: 'old_west_saloon', name: '🎰 Салон Дикого Запада', prompt: 'Wild West saloon, poker game, whiskey at bar, piano player, swinging doors, vintage western cinematic shot' },
  { id: 'ancient_persia', name: '🦁 Древняя Персия', prompt: 'Ancient Persian Empire, Persepolis palace, Immortal warriors, golden throne, epic Middle Eastern cinematic shot' },
  { id: 'inca_empire', name: '🏔️ Империя Инков', prompt: 'Inca Empire, Machu Picchu misty mountains, quipu records, sun temple, Andean civilization cinematic shot' },
  { id: 'pompeii', name: '🌋 Помпеи', prompt: 'Ancient Pompeii before Vesuvius eruption, Roman daily life, market and baths, Mount Vesuvius looming, dramatic cinematic shot' },
  { id: 'bronze_age', name: '🏺 Бронзовый век', prompt: 'Bronze Age Mediterranean, Minoan palaces on Crete, bronze swords and armor, early trade ships, epic ancient cinematic shot' },
  { id: 'huns_invasion', name: '🐎 Нашествие гуннов', prompt: 'Hunnic invasion of Europe, Attila the Hun on horseback, burning villages, nomadic warriors, epic ancient battle cinematic shot' },
  { id: 'roaring_20s_paris', name: '🥂 Париж 1920-х', prompt: '1920s Paris, Montmartre artists, jazz clubs, Hemingway and Fitzgerald, bohemian vintage cinematic shot' },
  { id: 'aztec_empire', name: '🦅 Империя Ацтеков', prompt: 'Aztec Empire, Tenochtitlan city, great pyramid, feathered warriors, gold and jade, epic cinematic shot' },
  { id: 'romanov_russia', name: '👑 Династия Романовых', prompt: 'Romanov dynasty Russia, imperial coronation, Faberge eggs, Russian Orthodox splendor, epic historical cinematic shot' },
  { id: 'titanic_era', name: '🛳️ Эпоха Титаника', prompt: 'Titanic era 1912, elegant Edwardian fashion, grand staircase, first class dining, period drama cinematic shot' },
  { id: 'soviet_space', name: '🚀 Советская космическая программа', prompt: 'Soviet space program, Sputnik and Vostok, cosmonauts, space race, socialist realism cinematic shot' },
  { id: 'ancient_carthage', name: '🐘 Древний Карфаген', prompt: 'Ancient Carthage, Hannibal with war elephants, Mediterranean port, Punic wars, epic historical cinematic shot' },
  { id: 'wild_africa', name: '🦁 Колониальная Африка', prompt: 'Colonial Africa, savanna exploration, vintage safari gear, Maasai warriors, epic adventure cinematic shot' }
];
module.exports = { HISTORY };
