// LITERATURE — 100 известнейших литературных произведений мира
const LITERATURE = [
  // --- Русская классика ---
  { id: 'war_and_peace', name: '📖 «Война и мир» — Л. Толстой', prompt: 'War and Peace by Leo Tolstoy, Napoleonic era Russia, grand ballroom, battlefield of Borodino, epic historical novel aesthetic, cinematic literary shot' },
  { id: 'crime_and_punishment', name: '📖 «Преступление и наказание» — Ф. Достоевский', prompt: 'Crime and Punishment by Dostoevsky, dark St Petersburg streets, Raskolnikov in his attic room, psychological tension, noir literary aesthetic' },
  { id: 'anna_karenina', name: '📖 «Анна Каренина» — Л. Толстой', prompt: 'Anna Karenina by Tolstoy, Russian aristocracy, train station, ballroom scene, tragic romance, elegant period literary aesthetic' },
  { id: 'master_and_margarita', name: '📖 «Мастер и Маргарита» — М. Булгаков', prompt: 'The Master and Margarita by Bulgakov, Soviet Moscow, talking cat Behemoth, Pontius Pilate, surreal magical realism aesthetic' },
  { id: 'brothers_karamazov', name: '📖 «Братья Карамазовы» — Ф. Достоевский', prompt: 'The Brothers Karamazov by Dostoevsky, Russian monastery, family drama, philosophical debate, intense psychological literary aesthetic' },
  { id: 'dead_souls', name: '📖 «Мёртвые души» — Н. Гоголь', prompt: 'Dead Souls by Gogol, provincial Russia, Chichikov in carriage, corrupt officials, satirical literary aesthetic' },
  { id: 'eugene_onegin', name: '📖 «Евгений Онегин» — А. Пушкин', prompt: 'Eugene Onegin by Pushkin, Russian countryside estate, Tatyana writing a letter, duel in snow, poetic literary aesthetic' },
  { id: 'doctor_zhivago', name: '📖 «Доктор Живаго» — Б. Пастернак', prompt: 'Doctor Zhivago by Pasternak, Russian Revolution, frozen landscape, love story, epic historical literary aesthetic' },
  { id: 'quiet_don', name: '📖 «Тихий Дон» — М. Шолохов', prompt: 'And Quiet Flows the Don by Sholokhov, Cossack village, Don river, WWI and Civil War, epic Russian literary aesthetic' },
  { id: 'gulliver', name: '📖 «Путешествия Гулливера» — Дж. Свифт', prompt: 'Gulliver\'s Travels by Swift, tied down by Lilliputians, giant in Brobdingnag, satirical adventure literary aesthetic' },
  { id: 'idiot', name: '📖 «Идиот» — Ф. Достоевский', prompt: 'The Idiot by Dostoevsky, Prince Myshkin in St Petersburg, Nastasya Filippovna, tragic beauty, psychological literary aesthetic' },
  { id: 'fathers_sons', name: '📖 «Отцы и дети» — И. Тургенев', prompt: 'Fathers and Sons by Turgenev, Russian countryside, nihilist Bazarov, generational conflict, realistic literary aesthetic' },
  { id: 'oblomov', name: '📖 «Обломов» — И. Гончаров', prompt: 'Oblomov by Goncharov, lying on sofa in old robe, St Petersburg apartment, laziness and dreams, satirical literary aesthetic' },
  { id: 'cherry_orchard', name: '📖 «Вишнёвый сад» — А. Чехов', prompt: 'The Cherry Orchard by Chekhov, cherry trees in bloom, Russian estate being sold, melancholy and change, theatrical literary aesthetic' },
  { id: 'we', name: '📖 «Мы» — Е. Замятин', prompt: 'We by Zamyatin, dystopian totalitarian future, glass city, numbers instead of names, futuristic literary aesthetic' },

  // --- Мировая классика ---
  { id: 'odyssey', name: '📖 «Одиссея» — Гомер', prompt: 'The Odyssey by Homer, Odysseus on ship, Cyclops cave, Penelope weaving, ancient Greek epic mythical literary aesthetic' },
  { id: 'iliad', name: '📖 «Илиада» — Гомер', prompt: 'The Iliad by Homer, Trojan War, Achilles vs Hector, walls of Troy, epic ancient Greek battle literary aesthetic' },
  { id: 'divine_comedy', name: '📖 «Божественная комедия» — Данте', prompt: 'Divine Comedy by Dante, nine circles of Hell, Virgil guiding, Beatrice in Paradise, medieval allegorical literary aesthetic' },
  { id: 'don_quixote', name: '📖 «Дон Кихот» — М. Сервантес', prompt: 'Don Quixote by Cervantes, windmill battle, Sancho Panza on donkey, Spanish plains, chivalric adventure literary aesthetic' },
  { id: 'hamlet', name: '📖 «Гамлет» — У. Шекспир', prompt: 'Hamlet by Shakespeare, Elsinore castle, skull of Yorick, to be or not to be, tragic theatrical literary aesthetic' },
  { id: 'romeo_juliet', name: '📖 «Ромео и Джульетта» — У. Шекспир', prompt: 'Romeo and Juliet by Shakespeare, Verona balcony, masquerade ball, tragic lovers, Renaissance Italian literary aesthetic' },
  { id: 'macbeth', name: '📖 «Макбет» — У. Шекспир', prompt: 'Macbeth by Shakespeare, Scottish moors, three witches, dagger hallucination, dark tragic theatrical literary aesthetic' },
  { id: 'faust', name: '📖 «Фауст» — И. Гёте', prompt: 'Faust by Goethe, Mephistopheles making a deal, scholar in study, Gretchen tragedy, German Romantic literary aesthetic' },
  { id: 'les_miserables', name: '📖 «Отверженные» — В. Гюго', prompt: 'Les Misérables by Hugo, barricades of Paris, Jean Valjean and Javert, French Revolution era, epic literary aesthetic' },
  { id: 'hunchback', name: '📖 «Собор Парижской Богоматери» — В. Гюго', prompt: 'The Hunchback of Notre Dame by Hugo, medieval Paris, Quasimodo on the cathedral, Esmeralda dancing, Gothic literary aesthetic' },
  { id: 'count_monte_cristo', name: '📖 «Граф Монте-Кристо» — А. Дюма', prompt: 'The Count of Monte Cristo by Dumas, Château d\'If prison, treasure island, revenge, swashbuckling adventure literary aesthetic' },
  { id: 'three_musketeers', name: '📖 «Три мушкетёра» — А. Дюма', prompt: 'The Three Musketeers by Dumas, all for one one for all, sword fights, Cardinal Richelieu, French adventure literary aesthetic' },
  { id: 'moby_dick', name: '📖 «Моби Дик» — Г. Мелвилл', prompt: 'Moby-Dick by Melville, whaling ship Pequod, Captain Ahab hunting the white whale, ocean adventure literary aesthetic' },
  { id: 'pride_prejudice', name: '📖 «Гордость и предубеждение» — Дж. Остин', prompt: 'Pride and Prejudice by Austen, English countryside estate, Mr Darcy and Elizabeth Bennet, Regency romance literary aesthetic' },
  { id: 'wuthering_heights', name: '📖 «Грозовой перевал» — Э. Бронте', prompt: 'Wuthering Heights by Brontë, Yorkshire moors, Heathcliff and Catherine, haunted love, Gothic romance literary aesthetic' },
  { id: 'jane_eyre', name: '📖 «Джейн Эйр» — Ш. Бронте', prompt: 'Jane Eyre by Brontë, Thornfield Hall, madwoman in attic, Mr Rochester, Victorian Gothic literary aesthetic' },
  { id: 'great_expectations', name: '📖 «Большие надежды» — Ч. Диккенс', prompt: 'Great Expectations by Dickens, Miss Havisham in wedding dress, Pip and Estella, Victorian London literary aesthetic' },
  { id: 'oliver_twist', name: '📖 «Оливер Твист» — Ч. Диккенс', prompt: 'Oliver Twist by Dickens, workhouse, Fagin\'s den, London streets, pickpockets, Victorian social literary aesthetic' },
  { id: 'a_christmas_carol', name: '📖 «Рождественская песнь» — Ч. Диккенс', prompt: 'A Christmas Carol by Dickens, Scrooge and ghosts, Victorian Christmas, Tiny Tim, heartwarming literary aesthetic' },
  { id: 'kafka_castle', name: '📖 «Замок» — Ф. Кафка', prompt: 'The Castle by Kafka, snow-covered village, bureaucratic labyrinth, mysterious castle above, surreal literary aesthetic' },
  { id: 'metamorphosis', name: '📖 «Превращение» — Ф. Кафка', prompt: 'The Metamorphosis by Kafka, Gregor Samsa as giant insect, bedroom, family horror, surreal existential literary aesthetic' },
  { id: 'hundred_years', name: '📖 «Сто лет одиночества» — Г. Маркес', prompt: 'One Hundred Years of Solitude by Márquez, Macondo village, Buendía family, magical realism, colorful literary aesthetic' },
  { id: 'love_in_time', name: '📖 «Любовь во время холеры» — Г. Маркес', prompt: 'Love in the Time of Cholera by Márquez, Caribbean port city, riverboat, elderly lovers, romantic magical realism literary aesthetic' },
  { id: 'catcher_in_rye', name: '📖 «Над пропастью во ржи» — Дж. Сэлинджер', prompt: 'The Catcher in the Rye by Salinger, Holden Caulfield in New York, red hunting hat, teenage rebellion literary aesthetic' },
  { id: 'gatsby', name: '📖 «Великий Гэтсби» — Ф. Фицджеральд', prompt: 'The Great Gatsby by Fitzgerald, lavish Long Island parties, green light, Jazz Age, decadent literary aesthetic' },
  { id: 'sun_also_rises', name: '📖 «И восходит солнце» — Э. Хемингуэй', prompt: 'The Sun Also Rises by Hemingway, Pamplona bull run, Paris cafés, lost generation, minimalist literary aesthetic' },
  { id: 'old_man_sea', name: '📖 «Старик и море» — Э. Хемингуэй', prompt: 'The Old Man and the Sea by Hemingway, fishing boat on Gulf Stream, marlin battle, Cuban coast, spare literary aesthetic' },
  { id: '1984', name: '📖 «1984» — Дж. Оруэлл', prompt: 'Nineteen Eighty-Four by Orwell, Big Brother watching, Winston and Julia, dystopian London, totalitarian literary aesthetic' },
  { id: 'animal_farm', name: '📖 «Скотный двор» — Дж. Оруэлл', prompt: 'Animal Farm by Orwell, farm animals rebelling, Napoleon the pig, allegory of revolution, satirical literary aesthetic' },
  { id: 'brave_new_world', name: '📖 «О дивный новый мир» — О. Хаксли', prompt: 'Brave New World by Huxley, test-tube babies, soma happiness, Fordian society, futuristic dystopian literary aesthetic' },
  { id: 'lolita', name: '📖 «Лолита» — В. Набоков', prompt: 'Lolita by Nabokov, American road trip, motels, Humbert Humbert, controversial literary aesthetic' },
  { id: 'ulysses', name: '📖 «Улисс» — Дж. Джойс', prompt: 'Ulysses by Joyce, Dublin city, Leopold Bloom, stream of consciousness, modernist literary aesthetic' },
  { id: 'portrait_artist', name: '📖 «Портрет художника в юности» — Дж. Джойс', prompt: 'A Portrait of the Artist as a Young Man by Joyce, Stephen Dedalus, Irish childhood, artistic awakening literary aesthetic' },
  { id: 'madame_bovary', name: '📖 «Мадам Бовари» — Г. Флобер', prompt: 'Madame Bovary by Flaubert, provincial France, Emma Bovary in romantic fantasy, tragic realism literary aesthetic' },
  { id: 'red_and_black', name: '📖 «Красное и чёрное» — Стендаль', prompt: 'The Red and the Black by Stendhal, Julien Sorel, French society, ambition and love, 19th century literary aesthetic' },
  { id: 'charterhouse_parma', name: '📖 «Пармская обитель» — Стендаль', prompt: 'The Charterhouse of Parma by Stendhal, Italian court intrigue, Napoleonic battles, romance, epic literary aesthetic' },
  { id: 'gargantua', name: '📖 «Гаргантюа и Пантагрюэль» — Ф. Рабле', prompt: 'Gargantua and Pantagruel by Rabelais, giants feasting, Renaissance satire, grotesque comedy literary aesthetic' },
  { id: 'candide', name: '📖 «Кандид» — Вольтер', prompt: 'Candide by Voltaire, best of all possible worlds, Pangloss, garden, satirical philosophical literary aesthetic' },
  { id: 'stranger', name: '📖 «Посторонний» — А. Камю', prompt: 'The Stranger by Camus, Meursault on beach, Algerian sun, absurdism, existential literary aesthetic' },
  { id: 'plague', name: '📖 «Чума» — А. Камю', prompt: 'The Plague by Camus, quarantined Oran city, Dr Rieux fighting epidemic, allegorical literary aesthetic' },
  { id: 'nausea', name: '📖 «Тошнота» — Ж.-П. Сартр', prompt: 'Nausea by Sartre, Roquentin in library, chestnut tree root, existential crisis, philosophical literary aesthetic' },
  { id: 'dracula', name: '📖 «Дракула» — Б. Стокер', prompt: 'Dracula by Stoker, Transylvanian castle, Count Dracula, vampire, Gothic horror literary aesthetic' },
  { id: 'frankenstein', name: '📖 «Франкенштейн» — М. Шелли', prompt: 'Frankenstein by Mary Shelley, monster creation scene, arctic ice, lightning, Gothic science fiction literary aesthetic' },
  { id: 'picture_of_dorian', name: '📖 «Портрет Дориана Грея» — О. Уайльд', prompt: 'The Picture of Dorian Gray by Wilde, portrait aging instead of Dorian, decadent London, aesthetic literary aesthetic' },
  { id: 'importance_being', name: '📖 «Как важно быть серьёзным» — О. Уайльд', prompt: 'The Importance of Being Earnest by Wilde, Victorian drawing room, mistaken identities, witty comedy literary aesthetic' },
  { id: 'tom_sawyer', name: '📖 «Приключения Тома Сойера» — М. Твен', prompt: 'The Adventures of Tom Sawyer by Twain, whitewashing fence, Mississippi river, cave adventure literary aesthetic' },
  { id: 'huck_finn', name: '📖 «Приключения Гекльберри Финна» — М. Твен', prompt: 'Adventures of Huckleberry Finn by Twain, raft on Mississippi, Jim the runaway slave, American classic literary aesthetic' },
  { id: 'decameron', name: '📖 «Декамерон» — Дж. Боккаччо', prompt: 'The Decameron by Boccaccio, Italian villa, plague escape, storytelling, Renaissance literary aesthetic' },
  { id: 'canterbury_tales', name: '📖 «Кентерберийские рассказы» — Дж. Чосер', prompt: 'The Canterbury Tales by Chaucer, pilgrims on road, Tabard Inn, medieval English storytelling literary aesthetic' },
  { id: 'to_kill_mockingbird', name: '📖 «Убить пересмешника» — Х. Ли', prompt: 'To Kill a Mockingbird by Harper Lee, small Alabama town, Atticus Finch in court, racial justice literary aesthetic' },
  { id: 'grapes_of_wrath', name: '📖 «Гроздья гнева» — Дж. Стейнбек', prompt: 'The Grapes of Wrath by Steinbeck, Dust Bowl, Joad family on Route 66, Great Depression literary aesthetic' },
  { id: 'of_mice_and_men', name: '📖 «О мышах и людях» — Дж. Стейнбек', prompt: 'Of Mice and Men by Steinbeck, California ranch, George and Lennie, American dream tragedy literary aesthetic' },
  { id: 'fahrenheit_451', name: '📖 «451 градус по Фаренгейту» — Р. Брэдбери', prompt: 'Fahrenheit 451 by Bradbury, fireman burning books, dystopian future, mechanical hound, futuristic literary aesthetic' },
  { id: 'kite_runner', name: '📖 «Бегущий за ветром» — Х. Хоссейни', prompt: 'The Kite Runner by Hosseini, Kabul Afghanistan, kite fighting, betrayal and redemption literary aesthetic' },
  { id: 'lotr', name: '📖 «Властелин колец» — Дж. Толкин', prompt: 'The Lord of the Rings by Tolkien, Frodo with the Ring, Mount Doom, epic fantasy quest literary aesthetic' },
  { id: 'hobbit', name: '📖 «Хоббит» — Дж. Толкин', prompt: 'The Hobbit by Tolkien, Bilbo Baggins, Smaug the dragon, Misty Mountains, adventure fantasy literary aesthetic' },
  { id: 'harry_potter', name: '📖 «Гарри Поттер» — Дж. Роулинг', prompt: 'Harry Potter by Rowling, Hogwarts castle, magic wand, Sorting Hat, magical school fantasy literary aesthetic' },
  { id: 'alice_adventures', name: '📖 «Алиса в Стране чудес» — Л. Кэрролл', prompt: 'Alice in Wonderland by Carroll, rabbit hole, Mad Hatter tea party, Cheshire Cat, whimsical fantasy literary aesthetic' },
  { id: 'winnie_pooh', name: '📖 «Винни-Пух» — А. Милн', prompt: 'Winnie-the-Pooh by Milne, Hundred Acre Wood, Pooh Bear and friends, childhood innocence literary aesthetic' },
  { id: 'little_prince', name: '📖 «Маленький принц» — А. де Сент-Экзюпери', prompt: 'The Little Prince by Saint-Exupéry, asteroid B-612, rose, fox, desert, poetic philosophical literary aesthetic' },
  { id: 'three_body', name: '📖 «Задача трёх тел» — Лю Цысинь', prompt: 'The Three-Body Problem by Liu Cixin, Cultural Revolution, alien contact, virtual reality, hard sci-fi literary aesthetic' },
  { id: 'dune', name: '📖 «Дюна» — Ф. Герберт', prompt: 'Dune by Herbert, Arrakis desert, giant sandworms, Paul Atreides, spice mining, epic sci-fi literary aesthetic' },
  { id: 'foundation', name: '📖 «Основание» — А. Азимов', prompt: 'Foundation by Asimov, galactic empire, psychohistory, Hari Seldon, futuristic sci-fi literary aesthetic' },
  { id: 'neuromancer', name: '📖 «Нейромант» — У. Гибсон', prompt: 'Neuromancer by Gibson, cyberspace matrix, cyberpunk future, Chiba City, neon noir sci-fi literary aesthetic' },
  { id: 'solaris', name: '📖 «Солярис» — С. Лем', prompt: 'Solaris by Lem, space station over alien ocean, sentient planet, ghostly visitors, philosophical sci-fi literary aesthetic' },
  { id: 'roadside_picnic', name: '📖 «Пикник на обочине» — Стругацкие', prompt: 'Roadside Picnic by Strugatsky brothers, Zone with alien artifacts, stalkers, eerie sci-fi literary aesthetic' },
  { id: 'master_sun', name: '📖 «Трудно быть богом» — Стругацкие', prompt: 'Hard to Be a God by Strugatsky, medieval planet, observer from Earth, feudal brutality, sci-fi literary aesthetic' },
  { id: '451_fahrenheit', name: '📖 «451° по Фаренгейту» — Р. Брэдбери', prompt: 'Fahrenheit 451 by Bradbury, book burning fireman, dystopian future, censorship, futuristic literary aesthetic' },
  { id: 'martian_chronicles', name: '📖 «Марсианские хроники» — Р. Брэдбери', prompt: 'The Martian Chronicles by Bradbury, colonizing Mars, Martian ruins, poetic sci-fi literary aesthetic' },
  { id: 'color_magic', name: '📖 «Цвет волшебства» — Т. Пратчетт', prompt: 'The Colour of Magic by Pratchett, Discworld, Rincewind the wizard, Ankh-Morpork, comic fantasy literary aesthetic' },
  { id: 'good_omens', name: '📖 «Благие знамения» — Пратчетт/Гейман', prompt: 'Good Omens by Pratchett and Gaiman, apocalypse, angel and demon, Antichrist, comedic fantasy literary aesthetic' },
  { id: 'american_gods', name: '📖 «Американские боги» — Н. Гейман', prompt: 'American Gods by Gaiman, Shadow Moon, old gods vs new, roadside America, mythical literary aesthetic' },
  { id: 'coraline', name: '📖 «Коралина» — Н. Гейман', prompt: 'Coraline by Gaiman, other mother, button eyes, secret door, dark fantasy literary aesthetic' },
  { id: 'wizard_of_oz', name: '📖 «Волшебник страны Оз» — Ф. Баум', prompt: 'The Wonderful Wizard of Oz by Baum, yellow brick road, Dorothy and Toto, Emerald City, fantasy literary aesthetic' },
  { id: 'treasure_island', name: '📖 «Остров сокровищ» — Р. Стивенсон', prompt: 'Treasure Island by Stevenson, pirate map, Long John Silver, Hispaniola ship, adventure literary aesthetic' },
  { id: 'strange_case_jekyll', name: '📖 «Странная история доктора Джекила» — Р. Стивенсон', prompt: 'Strange Case of Dr Jekyll and Mr Hyde by Stevenson, Victorian London, potion transformation, Gothic literary aesthetic' },
  { id: 'war_of_worlds', name: '📖 «Война миров» — Г. Уэллс', prompt: 'The War of the Worlds by Wells, Martian tripods invading, Victorian England, panic, sci-fi literary aesthetic' },
  { id: 'time_machine', name: '📖 «Машина времени» — Г. Уэллс', prompt: 'The Time Machine by Wells, time traveller, future Morlocks and Eloi, Victorian sci-fi literary aesthetic' },
  { id: 'invisible_man', name: '📖 «Человек-невидимка» — Г. Уэллс', prompt: 'The Invisible Man by Wells, bandaged stranger, scientific experiment gone wrong, suspense literary aesthetic' },
  { id: 'gone_with_wind', name: '📖 «Унесённые ветром» — М. Митчелл', prompt: 'Gone with the Wind by Mitchell, American Civil War South, Scarlett O\'Hara, Tara plantation, epic romance literary aesthetic' },
  { id: 'shantaram', name: '📖 «Шантарам» — Г. Робертс', prompt: 'Shantaram by Roberts, Bombay India, prison escape, slums and organized crime, epic adventure literary aesthetic' },
  { id: 'name_of_rose', name: '📖 «Имя розы» — У. Эко', prompt: 'The Name of the Rose by Eco, medieval monastery, mysterious murders, library labyrinth, detective literary aesthetic' },
  { id: 'foucault_pendulum', name: '📖 «Маятник Фуко» — У. Эко', prompt: 'Foucault\'s Pendulum by Eco, occult conspiracy, Paris museum, esoteric knowledge, intellectual thriller literary aesthetic' },
  { id: 'life_of_pi', name: '📖 «Жизнь Пи» — Я. Мартел', prompt: 'Life of Pi by Martel, lifeboat with Bengal tiger, Pacific Ocean, survival and faith literary aesthetic' },
  { id: 'alchemist', name: '📖 «Алхимик» — П. Коэльо', prompt: 'The Alchemist by Coelho, shepherd boy, Egyptian pyramids, personal legend, philosophical literary aesthetic' },
  { id: 'sherlock_holmes', name: '📖 «Шерлок Холмс» — А. К. Дойл', prompt: 'Sherlock Holmes by Doyle, 221B Baker Street, deerstalker hat, pipe, Victorian detective literary aesthetic' },
  { id: 'lost_world', name: '📖 «Затерянный мир» — А. К. Дойл', prompt: 'The Lost World by Doyle, Amazon plateau, dinosaurs, Professor Challenger, adventure literary aesthetic' },
  { id: 'captain_blood', name: '📖 «Одиссея капитана Блада» — Р. Сабатини', prompt: 'Captain Blood by Sabatini, pirate ship in Caribbean, swashbuckling doctor turned pirate, adventure literary aesthetic' },
  { id: 'countess_de_money', name: '📖 «Графиня де Монсоро» — А. Дюма', prompt: 'La Dame de Monsoreau by Dumas, French court intrigue, secret marriage, revenge, historical adventure literary aesthetic' },
  { id: 'flower_for_algernon', name: '📖 «Цветы для Элджернона» — Д. Киз', prompt: 'Flowers for Algernon by Keyes, Charlie Gordon, mouse Algernon, intelligence experiment, touching sci-fi literary aesthetic' },
  { id: 'sorrows_young_werther', name: '📖 «Страдания юного Вертера» — И. Гёте', prompt: 'The Sorrows of Young Werther by Goethe, blue coat and yellow vest, unrequited love, Romantic literary aesthetic' },
  { id: 'taras_bulba', name: '📖 «Тарас Бульба» — Н. Гоголь', prompt: 'Taras Bulba by Gogol, Zaporozhian Cossacks, Ukrainian steppe, father and sons, epic historical literary aesthetic' },
];
module.exports = { LITERATURE };
