// PERSONS — известные исторические личности
const PERSONS = [
  { id: 'caesar', name: '👑 Юлий Цезарь', prompt: 'powerful Roman general in white toga and golden laurel wreath, ancient Roman Senate, dramatic classical painting style' },
  { id: 'cleopatra', name: '👸 Клеопатра', prompt: 'Egyptian queen in golden headdress and royal linen, ancient Egyptian palace on the Nile, classical portrait painting' },
  { id: 'napoleon', name: '🎩 Наполеон Бонапарт', prompt: 'French emperor in bicorne hat and military coat, hand in waistcoat, battlefield background, romantic oil painting style' },
  { id: 'da_vinci', name: '🎨 Леонардо да Винчи', prompt: 'Renaissance man in Florentine attire, holding a sketch, workshop with his inventions, Renaissance portrait painting' },
  { id: 'mozart', name: '🎵 Вольфганг Амадей Моцарт', prompt: 'musical genius in powdered wig and 18th century court attire, harpsichord, Viennese palace, baroque painting style' },
  { id: 'einstein', name: '🧪 Альберт Эйнштейн', prompt: 'famous physicist with wild white hair, sweater, chalkboard with equations, warm sepia-toned portrait' },
  { id: 'ivan_grozny', name: '👑 Иван Грозный', prompt: 'Russian Tsar in ornate royal robes and Monomakh cap, gold and jewels, Kremlin chambers, medieval Russian icon painting style' },
  { id: 'peter_great', name: '⚓ Пётр Великий', prompt: 'Russian Emperor in military uniform and tricorn hat, shipyard or battlefield, 18th century portrait painting' },
  { id: 'catherine_ii', name: '👸 Екатерина II', prompt: 'Russian Empress in magnificent court gown and crown, ornate palace interior, 18th century rococo portrait painting' },
  { id: 'pushkin', name: '✍️ Александр Пушкин', prompt: 'great Russian poet in 19th century noble attire, sideburns, quill and paper, romantic portrait oil painting' },
  { id: 'tolstoy', name: '📚 Лев Толстой', prompt: 'Russian writer in peasant blouse and beard, Yasnaya Polyana estate, realist portrait painting style' },
  { id: 'dostoevsky', name: '📖 Фёдор Достоевский', prompt: 'Russian novelist in dark 19th century suit, intense gaze, St Petersburg study, brooding portrait painting' },
  { id: 'gagarin', name: '🚀 Юрий Гагарин', prompt: 'first cosmonaut in spacesuit with helmet, Vostok rocket behind, Soviet era portrait, realistic painting style' },
  { id: 'chaplin', name: '🎭 Чарли Чаплин', prompt: 'iconic silent film star in bowler hat with cane and small mustache, tramp costume, vintage film set aesthetic' },
  { id: 'lincoln', name: '🇺🇸 Авраам Линкольн', prompt: 'American president in black suit and tall hat, White House background, 19th century daguerreotype portrait style' },
  { id: 'marie_curie', name: '🔬 Мария Кюри', prompt: 'scientist in dark 19th century dress, laboratory with radium glow, Nobel prize atmosphere, classic portrait' },
  { id: 'shakespeare', name: '🎭 Уильям Шекспир', prompt: 'Elizabethan playwright in ruffled collar and doublet, Globe Theatre, Renaissance oil painting style' },
  { id: 'kings_arthur', name: '⚔️ Король Артур', prompt: 'legendary British king in shining armor, crown, holding Excalibur, Camelot castle, medieval tapestry style' },
  { id: 'nefertiti', name: '👑 Нефертити', prompt: 'Egyptian queen in tall blue crown, elegant royal linen, ancient Thebes, bust portrait in Egyptian mural style' },
  { id: 'alexander_macedon', name: '⚔️ Александр Македонский', prompt: 'Macedonian king in bronze armor and flowing cape, Battle of Gaugamela, classical Greek hero painting' },
  { id: 'beethoven', name: '🎼 Людвиг ван Бетховен', prompt: 'composer with intense expression, wild gray hair, composing at piano, Vienna, romantic period oil painting' },
  { id: 'columbus', name: '⛵ Христофор Колумб', prompt: 'explorer in 15th century Spanish attire, ships Niña Pinta Santa Maria, discovering America, Renaissance painting' },
  { id: 'van_gogh', name: '🌻 Винсент Ван Гог', prompt: 'painter with straw hat and bandaged ear, easel with sunflowers, Arles countryside, post-impressionist painting style' },
  { id: 'newton', name: '🍎 Исаак Ньютон', prompt: 'scientist in 17th century wig and coat, under apple tree, prism and light, classical portrait painting' },
  { id: 'rasputin', name: '🔮 Григорий Распутин', prompt: 'mysterious mystic with long beard and dark Russian coat, piercing eyes, Imperial Russia court, dramatic portrait' },
  { id: 'merlin', name: '🧙‍♂️ Мерлин', prompt: 'legendary wizard in druid robes and long beard, staff with glowing crystal, mystical forest, medieval illuminated manuscript style' },
  { id: 'mendeleev', name: '🧪 Дмитрий Менделеев', prompt: 'Russian chemist with magnificent beard and 19th century coat, periodic table, laboratory, classic portrait' },
  { id: 'suvorov', name: '🎖️ Александр Суворов', prompt: 'Russian military commander in ornate uniform with medals, crossing the Alps, battle map, 18th century military portrait' },
  { id: 'lomonosov', name: '🔭 Михаил Ломоносов', prompt: 'Russian scientist-poet in 18th century wig and coat, laboratory and books, Northern Lights, rococo portrait' },
  { id: 'tchaikovsky', name: '🎵 Пётр Чайковский', prompt: 'Russian composer in 19th century suit and beard, conducting orchestra, ballet theater, romantic portrait style' },
  { id: 'stalin', name: '👨‍✈️ Иосиф Сталин', prompt: 'Soviet leader in military uniform, mustache, Kremlin office, pipesmoke, socialist realism painting style' },
  { id: 'lenin', name: '✊ Владимир Ленин', prompt: 'Russian revolutionary in suit and cap, making speech from armored car, Soviet era poster style' },
  { id: 'freud', name: '🛋️ Зигмунд Фрейд', prompt: 'father of psychoanalysis with cigar, Vienna study with couch, bookshelves, early 20th century portrait' },
  { id: 'mandela', name: '✊ Нельсон Мандела', prompt: 'South African leader in colorful shirt, warm smile, courthouse or prison cell background, modern portrait style' },
  { id: 'gandhi', name: '🕊️ Махатма Ганди', prompt: 'Indian independence leader in white dhoti and shawl, round glasses, peaceful protest scene, documentary style' },
  { id: 'kutuzov', name: '🎖️ Михаил Кутузов', prompt: 'Russian field marshal with eye patch and uniform, Borodino battle map, 1812 war council, imperial portrait' },
  { id: 'yesenin', name: '🌾 Сергей Есенин', prompt: 'Russian poet with blond hair, peasant shirt and waistcoat, birch trees, Russian countryside, lyrical portrait' },
  { id: 'mayakovsky', name: '📯 Владимир Маяковский', prompt: 'Russian futurist poet in bold suit, dramatic pose, revolutionary posters, avant-garde painting style' },
  { id: 'gogol', name: '👻 Николай Гоголь', prompt: 'Russian writer in long coat and hat, mysterious expression, St Petersburg rooftops, dark romantic portrait' },
  { id: 'tsiolkovsky', name: '🚀 Константин Циолковский', prompt: 'Russian rocket scientist in suit, telescope and rocket models, starry sky, visionary portrait style' },
  { id: 'pavlov', name: '🔬 Иван Павлов', prompt: 'Russian physiologist with white beard and lab coat, experimental apparatus, dog laboratory, scientific portrait' },
  { id: 'nietzsche', name: '🧔 Фридрих Ницше', prompt: 'German philosopher with huge mustache, deep thinking pose, Alpine mountains, dramatic philosophical portrait' },
  { id: 'mona_lisa_self', name: '🖼️ Личность в стиле Моны Лизы', prompt: 'Renaissance figure with mysterious smile, folded hands, Tuscan landscape background, sfumato technique, Da Vinci style' },
  { id: 'winston_churchill', name: '💼 Уинстон Черчилль', prompt: 'British PM with cigar and bowler hat, V-sign, wartime bunker, 1940s portrait painting style' },
  { id: 'queen_victoria', name: '👑 Королева Виктория', prompt: 'British monarch in black mourning dress and white lace, royal crown, Victorian palace, 19th century portrait' },
  { id: 'galileo', name: '🔭 Галилео Галилей', prompt: 'Italian astronomer in Renaissance attire, pointing at stars, telescope, Pisa leaning tower, baroque painting' },
  { id: 'edison', name: '💡 Томас Эдисон', prompt: 'American inventor in suit and vest, holding lightbulb, Menlo Park lab, sepia photograph style' },
  { id: 'tesla', name: '⚡ Никола Тесла', prompt: 'inventor in elegant suit, electrical coils with lightning, lab with Tesla coil, sepia documentary style' },
  { id: 'repin', name: '🎨 Илья Репин', prompt: 'Russian painter with palette and brush, Cossacks or Volga boatmen canvas behind, academic portrait' },
  { id: 'chekhov', name: '🖋️ Антон Чехов', prompt: 'Russian writer-doctor in pince-nez glasses and suit, Melikhovo estate, cherry orchard, quiet literary portrait' },
  { id: 'hitler', name: '❌ Адольф Гитлер', prompt: 'historical figure in military coat and small mustache, Nazi rally backdrop, 1930s documentary style portrait' },
  { id: 'cleopatra_mark', name: '💕 Марк Антоний', prompt: 'Roman general in military armor, Roman Republic, dramatic ancient Roman painting style' },
  { id: 'kant', name: '🧠 Иммануил Кант', prompt: 'German philosopher in 18th century wig and coat, Königsberg study, clockwork precision, Enlightenment portrait' },
  { id: 'magellan', name: '🌏 Фернан Магеллан', prompt: 'Portuguese explorer in 16th century attire, globe and compass, ship at sea, Age of Discovery painting' },
  { id: 'kuzma_minin', name: '✊ Кузьма Минин', prompt: 'Russian patriotic leader in medieval merchant attire, Minin and Pozharsky monument, 17th century Moscow, historical painting' },
  { id: 'napoleon_russian', name: '❄️ Наполеон в России', prompt: 'Napoleon in winter coat, retreating from Moscow snow, Borodino aftermath, 1812 war painting' },
  { id: 'roerich', name: '🎨 Николай Рерих', prompt: 'Russian painter-philosopher in meditation pose, Himalayan mountains behind, mystical Agni Yoga style painting' },
  { id: 'prokofiev', name: '🎵 Сергей Прокофьев', prompt: 'Russian composer in 20th century suit, piano and orchestral score, modern classical portrait' },
  { id: 'shostakovich', name: '🎼 Дмитрий Шостакович', prompt: 'Russian composer with thick glasses, Leningrad symphony score, dramatic Soviet era portrait' },
  { id: 'vavilov', name: '🌾 Николай Вавилов', prompt: 'Russian botanist-geneticist in fieldwork hat, wheat fields, botanical collections, scientific explorer portrait' },
  { id: 'korolev', name: '🚀 Сергей Королёв', prompt: 'Soviet chief rocket engineer in suit, Sputnik and rocket designs, space program, documentary portrait' },
  { id: 'sakharov', name: '☮️ Андрей Сахаров', prompt: 'Soviet physicist and dissident in suit, nuclear physics and human rights, Gorky exile, intellectual portrait' },
  { id: 'solzhenitsyn', name: '📯 Александр Солженицын', prompt: 'Russian writer-dissident in beard and Gulag jacket, camp barracks, matryoshka, documentary portrait style' },
  { id: 'vysotsky', name: '🎸 Владимир Высоцкий', prompt: 'Russian poet-singer with guitar and cigarettes, theater stage, 1970s Soviet apartment, raw documentary style' },
  { id: 'tereshkova', name: '👩‍🚀 Валентина Терешкова', prompt: 'first woman in space, Soviet cosmonaut in bright orange suit and helmet, Vostok rocket, socialist portrait' },
  { id: 'mendeleev_2', name: '🧪 Дмитрий Менделеев', prompt: 'Russian scientist at desk with periodic table elements, chemistry lab, 19th century academic portrait' },
  { id: 'frida_kahlo', name: '🌸 Фрида Кало', prompt: 'Mexican painter in colorful traditional dress and flower crown, unibrow, surrounded by Casa Azul garden, surrealist portrait' },
  { id: 'jung', name: '🧠 Карл Юнг', prompt: 'Swiss psychiatrist in 20th century attire, Bollingen Tower, mystical symbols, analytical psychology portrait' },
  { id: 'gorky', name: '✍️ Максим Горький', prompt: 'Russian writer in cap and peasant coat, Capri or Moscow, socialist realism literary portrait painting' },
  { id: 'blok', name: '🌹 Александр Блок', prompt: 'Russian symbolist poet in elegant 20th century attire, St Petersburg snowy streets, beautiful lady verse, symbolist portrait' },
  { id: 'chaliapin', name: '🎤 Фёдор Шаляпин', prompt: 'Russian opera singer in flowing cape and hat, dramatic stage presence, Boris Godunov role, theatrical portrait' },
  { id: 'chagall', name: '🎨 Марк Шагал', prompt: 'Russian-French artist in whimsical painter attire, floating figures and Vitebsk village, dreamlike Chagall painting style' },
  { id: 'kandinsky', name: '🔴 Василий Кандинский', prompt: 'Russian abstract artist in suit, abstract colorful canvas behind, Bauhaus school, expressionist portrait' },
  { id: 'malevich', name: '◼️ Казимир Малевич', prompt: 'Russian avant-garde artist in black square backdrop, suprematist art, 1920s constructivist portrait' },
  { id: 'einstein_young', name: '⚛️ Молодой Эйнштейн', prompt: 'young patent clerk with curly hair, Bern streets, relativity thought experiment, early 1900s portrait' }
];
module.exports = { PERSONS };
