// LOCATIONS — 100 famous world locations
const LOCATIONS = [
  { id: 'acropolis', name: '🏛️ Акрополь', prompt: 'person at the Acropolis, Athens, Parthenon temple, ancient Greece, marble columns, blue sky' },
  { id: 'alhambra', name: '🕌 Альгамбра', prompt: 'person at Alhambra, Granada Spain, Moorish palace, intricate tilework, Generalife gardens' },
  { id: 'angkor_wat', name: '🛕 Ангкор-Ват', prompt: 'person at Angkor Wat, Cambodia, ancient Khmer temple, sunrise reflection, moss-covered stones' },
  { id: 'temples_bagan', name: '🛕 Баган', prompt: 'person in Bagan, Myanmar, thousands of ancient Buddhist temples on plains, hot air balloon view' },
  { id: 'big_ben', name: '🕰️ Биг-Бен', prompt: 'person with Big Ben and Parliament behind, London, Gothic clock tower, River Thames' },
  { id: 'bondi_beach', name: '🏄 Бонди-Бич', prompt: 'person at Bondi Beach, Sydney Australia, golden sand, surfers, coastal walk, blue Pacific' },
  { id: 'bora_bora', name: '🏝️ Бора-Бора', prompt: 'person on Bora Bora, crystal turquoise lagoon, overwater bungalow, Mount Otemanu, tropical paradise' },
  { id: 'buckingham', name: '👑 Букингемский дворец', prompt: 'person at Buckingham Palace, London, royal palace, guards in bearskin hats, gates' },
  { id: 'burj_khalifa', name: '🏙️ Бурдж-Халифа', prompt: 'person in front of Burj Khalifa, Dubai, tallest building in the world, modern glass architecture' },
  { id: 'great_wall', name: '🧱 Великая Китайская стена', prompt: 'person on the Great Wall of China, mountain landscape, ancient stone wall curving into distance' },
  { id: 'venice_canals', name: '🚣 Венеция', prompt: 'person on a gondola in Venice canal, historic Italian buildings, romantic bridge' },
  { id: 'versailles', name: '👑 Версаль', prompt: 'person at Palace of Versailles, France, Hall of Mirrors, grand gardens, French royalty' },
  { id: 'hanging_gardens', name: '🌿 Висячие сады Семирамиды', prompt: 'person at the Hanging Gardens of Babylon concept, Iraq, terraced lush gardens, ancient wonder' },
  { id: 'victoria_falls', name: '💦 Водопад Виктория', prompt: 'person at Victoria Falls, Zambia-Zimbabwe, massive waterfall, mist spray, rainbow' },
  { id: 'iguazu', name: '🌊 Водопад Игуасу', prompt: 'person at Iguazu Falls, Argentina-Brazil border, massive waterfall system, tropical jungle' },
  { id: 'avenue_canova', name: '🖼️ Галерея Уффици', prompt: 'person at the Uffizi Gallery, Florence, Renaissance art, Botticelli and da Vinci, historic gallery' },
  { id: 'himalayas', name: '🏔️ Гималаи', prompt: 'person in the Himalayas, Nepal, snowy mountain peaks, Everest base camp, Tibetan prayer flags' },
  { id: 'hollywood_sign', name: '🎬 Голливуд', prompt: 'person in front of the Hollywood sign, Los Angeles, palm trees, California sunshine' },
  { id: 'reykjavik', name: '♨️ Голубая лагуна', prompt: 'person in Blue Lagoon, Iceland, geothermal spa, milky blue water, volcanic landscape' },
  { id: 'altai_mountains', name: '🏔️ Горный Алтай', prompt: 'person in the Altai Mountains, Siberia, pristine nature, wild rivers, nomadic culture' },
  { id: 'monaco_gp', name: '🏎️ Гран-при Монако', prompt: 'person at Monaco Grand Prix, luxury yachts and F1 cars, harbor circuit, Monte Carlo glamour' },
  { id: 'grand_bazaar', name: '🛍️ Гранд-базар', prompt: 'person at the Grand Bazaar, Istanbul, vast covered market, colorful spices, Turkish lamps' },
  { id: 'grand_canyon', name: '🏜️ Гранд-Каньон', prompt: 'person at the Grand Canyon, Arizona, vast colorful rock formations, sunset orange light' },
  { id: 'dubrovnik', name: '🏰 Дубровник', prompt: 'person in Dubrovnik, Croatia, ancient city walls, terracotta roofs, Adriatic sea, Game of Thrones' },
  { id: 'lake_geneva', name: '🏞️ Женевское озеро', prompt: 'person at Lake Geneva, Switzerland, Jet deau fountain, Alps in background, elegant promenade' },
  { id: 'neuschwanstein', name: '🏰 Замок Нойшванштайн', prompt: 'person in front of Neuschwanstein Castle, Bavaria Germany, fairy-tale castle, Alpine forest' },
  { id: 'fushun', name: '🏯 Запретный город', prompt: 'person at the Forbidden City, Beijing, Imperial Palace, red and gold architecture, Chinese history' },
  { id: 'kinkaku', name: '🏯 Золотой павильон', prompt: 'person at Kinkaku-ji Golden Pavilion, Kyoto Japan, gold leaf temple, reflection pond' },
  { id: 'pamukkale_2', name: '🏛️ Иераполис', prompt: 'person at Hierapolis ancient city, Turkey, ruins above Pamukkale, Roman theater' },
  { id: 'antelope_canyon', name: '🎨 Каньон Энтелоп', prompt: 'person in Antelope Canyon, Arizona, narrow slot canyon, light beams, orange sandstone' },
  { id: 'cappadocia', name: '🎈 Каппадокия', prompt: 'person in Cappadocia, Turkey, hot air balloons in sky, fairy chimney rock formations, sunrise' },
  { id: 'quebec_city', name: '🏘️ Квебек-Сити', prompt: 'person in Old Quebec, Canada, Chateau Frontenac, cobblestone streets, French Canadian charm' },
  { id: 'keukenhof', name: '🌷 Кёкенхоф', prompt: 'person in Keukenhof gardens, Netherlands, millions of tulips in bloom, windmill, colorful flowers' },
  { id: 'colosseum', name: '🏛️ Колизей', prompt: 'person in front of the Roman Colosseum, ancient Rome architecture, warm golden stone, tourist atmosphere' },
  { id: 'kotor', name: '🏘️ Котор', prompt: 'person in Kotor Bay, Montenegro, medieval walled town, fjord-like bay, Adriatic Sea' },
  { id: 'red_square', name: '🔴 Красная площадь', prompt: 'person on Red Square, Moscow, St Basil Cathedral, colorful domes, cobblestone square' },
  { id: 'oche_de_la', name: '☃️ Ледник Перито-Морено', prompt: 'person at Perito Moreno Glacier, Argentina, massive blue ice wall, Patagonia, glacier calving' },
  { id: 'louvre', name: '🎨 Лувр', prompt: 'person in front of the Louvre Pyramid, Paris, glass pyramid entrance, historic palace museum' },
  { id: 'mona_lisa', name: '🖼️ Лувр-Мона Лиза', prompt: 'person admiring the Mona Lisa in the Louvre, Paris, museum gallery, crowd of art lovers' },
  { id: 'maldives', name: '🏝️ Мальдивы', prompt: 'person on a Maldives beach, overwater bungalow, crystal turquoise water, tropical paradise' },
  { id: 'matterhorn', name: '⛰️ Маттерхорн', prompt: 'person with the Matterhorn mountain, Swiss Alps, iconic pyramid peak, Zermatt ski resort' },
  { id: 'machu_picchu', name: '🏔️ Мачу-Пикчу', prompt: 'person at Machu Picchu, Incan ruins in the Andes, misty mountain clouds, Peru, ancient terraces' },
  { id: 'dead_sea', name: '🧂 Мёртвое море', prompt: 'person floating in the Dead Sea, Israel-Jordan, salt crystals, mineral water, desert mountains' },
  { id: 'metropolitan_ny', name: '🎭 Метрополитен-музей', prompt: 'person at the Metropolitan Museum of Art, New York, grand staircase, classical art' },
  { id: 'milford_sound', name: '⛰️ Милфорд-Саунд', prompt: 'person at Milford Sound, New Zealand, dramatic fiord, waterfalls, rainforest, misty mountains' },
  { id: 'monte_carlo', name: '🎰 Монте-Карло', prompt: 'person at Monte Carlo, Monaco, luxury casino, harbor with yachts, Formula 1 streets' },
  { id: 'moscow_city', name: '🏙️ Москва-Сити', prompt: 'person with Moscow City skyscrapers behind, modern business district, Russia' },
  { id: 'kremlin', name: '🏘️ Московский Кремль', prompt: 'person in front of the Kremlin, Moscow, red brick walls, colorful cathedral domes, Red Square' },
  { id: 'golden_gate', name: '🌉 Мост Золотые Ворота', prompt: 'person on the Golden Gate Bridge, San Francisco, orange suspension bridge, foggy bay background' },
  { id: 'meiji_shrine', name: '⛩️ Мэйдзи Дзингу', prompt: 'person at Meiji Shrine, Tokyo, massive torii gate, forested path, Shinto tradition' },
  { id: 'glacier_nat', name: '🏔️ Национальный парк Ледниковый', prompt: 'person at Glacier National Park, Montana USA, Going-to-the-Sun Road, alpine meadows' },
  { id: 'niagara_falls', name: '🌊 Ниагарский водопад', prompt: 'person at Niagara Falls, massive waterfall, mist and rainbow, Canadian-US border' },
  { id: 'fjord_norway', name: '🏞️ Норвежский фьорд', prompt: 'person at Geirangerfjord, Norway, deep blue fjord, waterfalls, steep green cliffs, Nordic scenery' },
  { id: 'vinpearl', name: '🌴 Нячанг', prompt: 'person at Nha Trang beach, Vietnam, white sand, palm trees, Hon Mun island view' },
  { id: 'baikal', name: '💎 Озеро Байкал', prompt: 'person at Lake Baikal, Siberia, crystal clear ice in winter, deepest lake, stunning blue ice formations' },
  { id: 'lake_bled', name: '🏘️ Озеро Блед', prompt: 'person at Lake Bled, Slovenia, island church, medieval castle cliff, Alpine lake' },
  { id: 'lake_como', name: '🏞️ Озеро Комо', prompt: 'person at Lake Como, Italy, elegant lakeside villas, Alpine backdrop, serene blue water' },
  { id: 'banff', name: '🏔️ Озеро Луиз', prompt: 'person at Lake Louise, Banff Canada, turquoise glacial lake, Rocky Mountains, pine forest' },
  { id: 'sochi_park', name: '🌊 Олимпийский парк Сочи', prompt: 'person at Sochi Olympic Park, Russia, Black Sea coast, modern stadiums, palm trees' },
  { id: 'sydney_opera', name: '🎭 Оперный театр Сиднея', prompt: 'person in front of Sydney Opera House, harbor bridge, bright Australian sun, waterfront' },
  { id: 'pamir', name: '🏔️ Памир', prompt: 'person in the Pamir Mountains, Tajikistan, high altitude landscape, nomadic yurts, rugged peaks' },
  { id: 'pamukkale', name: '🛁 Памуккале', prompt: 'person at Pamukkale, Turkey, white travertine terraces, thermal pools, ancient Hierapolis ruins' },
  { id: 'metro_st_petersburg', name: '🚇 Петербургское метро', prompt: 'person in St Petersburg metro station, Russia, ornate crystal chandeliers, marble, palace-like' },
  { id: 'petra', name: '🏚️ Петра', prompt: 'person at Petra, Jordan, ancient rock-cut architecture, Al-Khazneh treasury, desert canyons' },
  { id: 'pisa', name: '🗼 Пизанская башня', prompt: 'person holding up the Leaning Tower of Pisa, Italy, tilted bell tower, Piazza dei Miracoli' },
  { id: 'victoria_peak', name: '🏙️ Пик Виктория', prompt: 'person at Victoria Peak, Hong Kong, skyline view over harbor, towering skyscrapers' },
  { id: 'pyramids', name: '🔺 Пирамиды Гизы', prompt: 'person with the Great Pyramids of Giza behind, Egyptian desert, camel, golden sand and sky' },
  { id: 'plaza_mayor', name: '🌆 Пласа Майор', prompt: 'person at Plaza Mayor, Madrid, historic Spanish square, 17th century architecture, cafes' },
  { id: 'amalfi_coast', name: '🏘️ Побережье Амальфи', prompt: 'person on the Amalfi Coast, Italy, colorful cliffside villages, Positano, Mediterranean sea' },
  { id: 'potala', name: '🏛️ Потала', prompt: 'person at Potala Palace, Lhasa Tibet, massive white and red fortress, Himalayan monastery' },
  { id: 'prague_castle', name: '🏰 Пражский град', prompt: 'person at Prague Castle, Czech Republic, Gothic cathedral, Golden Lane, Charles Bridge view' },
  { id: 'fjord_2', name: '🏔️ Прекестулен', prompt: 'person at Preikestolen, Norway, flat cliff plateau overlooking Lysefjord, dramatic drop' },
  { id: 'colosseum_2', name: '🏟️ Римский форум', prompt: 'person at the Roman Forum, ancient ruins, Rome, historic pillars, Italian sunshine' },
  { id: 'sagrada', name: '⛪ Саграда-Фамилия', prompt: 'person in front of Sagrada Familia, Barcelona, Gaudi architecture, intricate facades, Spain' },
  { id: 'santorini', name: '🌅 Санторини', prompt: 'person in Santorini, Greece, white and blue buildings, caldera view, Mediterranean sunset' },
  { id: 'safari', name: '🦁 Сафари в Серенгети', prompt: 'person on safari in Serengeti, Tanzania, savanna landscape, wildlife, African sunset' },
  { id: 'sahara', name: '🐪 Сахара', prompt: 'person in the Sahara Desert, Morocco, golden sand dunes, camel caravan, dramatic sunset' },
  { id: 'fuji_shrine', name: '⛩️ Святилище Фусими Инари', prompt: 'person at Fushimi Inari shrine, Kyoto Japan, thousands of vermillion torii gates, forest path' },
  { id: 'aurora', name: '🌌 Северное сияние', prompt: 'person watching Northern Lights, aurora borealis, starry sky, snow-covered Arctic landscape' },
  { id: 'shibuya', name: '🚦 Сибуя', prompt: 'person at Shibuya Crossing, Tokyo, neon lights, crowded pedestrian scramble, Japan energy' },
  { id: 'notre_dame', name: '⛪ Собор Парижской Богоматери', prompt: 'person in front of Notre-Dame Cathedral, Paris, Gothic architecture, rose window, Seine river' },
  { id: 'salar_uyuni', name: '🪞 Солончак Уюни', prompt: 'person at Salar de Uyuni, Bolivia, largest salt flat in the world, mirror effect when flooded' },
  { id: 'sossusvlei', name: '🏜️ Соссусфлей', prompt: 'person at Sossusvlei, Namibia, tallest red sand dunes in the world, dead camel thorn trees' },
  { id: 'statue_liberty', name: '🗽 Статуя Свободы', prompt: 'person with Statue of Liberty behind, New York harbor, blue sky, American icon' },
  { id: 'christ_rio', name: '✝️ Статуя Христа-Искупителя', prompt: 'person at Christ the Redeemer statue, Rio de Janeiro, Corcovado mountain, city view' },
  { id: 'stonehenge', name: '🪨 Стоунхендж', prompt: 'person at Stonehenge, England, ancient megalithic stones, misty green field, mysterious atmosphere' },
  { id: 'taj_mahal', name: '🕌 Тадж-Махал', prompt: 'person in front of Taj Mahal, Agra India, white marble mausoleum, sunrise light, reflection pool' },
  { id: 'times_square', name: '🌃 Таймс-сквер', prompt: 'person in Times Square, New York City, massive digital billboards, bright lights, Broadway' },
  { id: 'giants_causeway', name: '🪨 Тропа великанов', prompt: 'person at Giant Causeway, Northern Ireland, hexagonal basalt columns, dramatic coastline' },
  { id: 'tulum', name: '🌴 Тулум', prompt: 'person at Tulum ruins, Mexico, Mayan temple on cliff above Caribbean turquoise sea' },
  { id: 'uluru', name: '🪨 Улуру', prompt: 'person at Uluru, Australia, massive red monolith, outback desert, Aboriginal sacred site at sunset' },
  { id: 'trevi', name: '🪙 Фонтан Треви', prompt: 'person at the Trevi Fountain, Rome, Baroque fountain, throwing coin, Baroque sculptures' },
  { id: 'mount_fuji', name: '🗻 Фудзияма', prompt: 'person with Mount Fuji background, Japan, iconic snow-capped volcano, cherry blossoms in spring' },
  { id: 'hawa_mahal', name: '🏠 Хава-Махал', prompt: 'person at Hawa Mahal, Jaipur India, Palace of Winds, pink sandstone, Rajasthani architecture' },
  { id: 'hallstatt', name: '🏘️ Хальштатт', prompt: 'person in Hallstatt, Austria, alpine village on lake, pastel houses, mountain backdrop' },
  { id: 'harbin_ice', name: '❄️ Харбинский фестиваль', prompt: 'person at Harbin Ice Festival, China, huge illuminated ice sculptures, winter wonderland' },
  { id: 'bali_temple', name: '🛕 Храм Улувату', prompt: 'person at Uluwatu Temple, Bali, cliff-edge Hindu temple, Indian Ocean sunset, tropical' },
  { id: 'central_park', name: '🌳 Центральный парк', prompt: 'person in Central Park, New York City, autumn leaves, skyline view, horse carriage' },
  { id: 'cinque_terre', name: '🎨 Чинкве-Терре', prompt: 'person in Cinque Terre, Italy, colorful houses on cliff, Ligurian sea, vineyard terraces' },
  { id: 'chichen_itza', name: '🏛️ Чичен-Ица', prompt: 'person at Chichen Itza, Mexico, Mayan pyramid of Kukulcan, ancient ruins, Yucatan jungle' },
  { id: 'edinburg', name: '🏰 Эдинбургский замок', prompt: 'person at Edinburgh Castle, Scotland, medieval fortress, Royal Mile, Scottish skyline' },
  { id: 'eiffel', name: '🗼 Эйфелева башня', prompt: 'person in front of the Eiffel Tower, Paris, France, elegant European backdrop, cloudy sky, iconic landmark' }
];
module.exports = { LOCATIONS };